### ISSUE TITLE
Убрать данные в .env файл

### ISSUE THREAD

**Issue by pavivin** [Sinlew/admission-monitoring-bot#11]
https://github.com/Sinlew/admission-monitoring-bot/blob/91e2f7cfc473dcceb71a47c61366d2e9346e045d/api/parser_sql_filler/config/config.py#L4C10-L4C10

Такого рода переменные лучше скрыть и считывать из env файла

у pydantic для его есть base settings

**Comment by Sinlew** [comment]
исправил
