### ISSUE TITLE
Лишняя функция

### ISSUE THREAD

**Issue by pavivin** [Sinlew/admission-monitoring-bot#4]
https://github.com/Sinlew/admission-monitoring-bot/blob/91e2f7cfc473dcceb71a47c61366d2e9346e045d/api/parser_sql_filler/sqlalc.py#L45C10-L45C10

при заполненной бд очень сильно может нагрузить

**Comment by Sinlew** [comment]
изменил на проверку первого элемента чтобы избежать большой нагрузки
