### ISSUE TITLE
Явно возвращать ошибку

### ISSUE THREAD

**Issue by pavivin** [Sinlew/admission-monitoring-bot#6]
https://github.com/Sinlew/admission-monitoring-bot/blob/91e2f7cfc473dcceb71a47c61366d2e9346e045d/api/parser_sql_filler/sqlalc.py#L33-L36

в использовании апи хорошим подходом считается обработка ошибок, так как True и False недостаточно, False это всё что не хорошо, нет данных, ошибка #1, ошибка #2

**Comment by pavivin** [comment]
https://habr.com/ru/companies/otus/articles/570882/

**Comment by Sinlew** [comment]
данная функция нужна для внутренних проверок и не требует вызова ошибок

**Comment by pavivin** [comment]
Тогда хотя бы return len(user) == 0 -> Bool

либо bool(user)

**Comment by pavivin** [comment]
Для списка лучше использовать название user_list
