### ISSUE TITLE
не использовать в большом количестве позиционные аргументы

### ISSUE THREAD

**Issue by pavivin** [Sinlew/admission-monitoring-bot#9]
https://github.com/Sinlew/admission-monitoring-bot/blob/91e2f7cfc473dcceb71a47c61366d2e9346e045d/api/parser_sql_filler/pars_main.py#L34

при таком количестве аргументов, можно перепутать переменные местами и обновить не то, лучше передавать по ключу

**Comment by Sinlew** [comment]
добавил ключи
